### ISSUE TITLE
Any ideas on what I could use to remove the url shortener/clipper?

### ISSUE THREAD

**Issue by God-status** [PinkDev1/PimEyes-Crack-UserStyle#3]
Hey, there thx for the addon, works great! Could you plz elaborate on what method (or specific tool) could be used to view the entire url? Thx in advance!

**Comment by God-status** [comment]
Hey, thx!

**Comment by PinkDev1** [comment]
After a quick inspection with BurpSuite, it seems the URLs are cropped from the API itself, before being sent to the client. Because it's done server side, so there's nothing we can do about it. Unless we try to pwn the API, but that wouldn't be worth it.

Just for the record: The images are encoded in base64 in the response of the POST request to the server. These base64-encoded images are already blurred.

BUT: In the responses, something that could be important is returned, but never displayed on the actual results page: the `sourceUrl` field, and the `crawledAt` field. The sourceUrl field is still cropped to 30 chars, but it might give some extra insight on the result image. The `crawledAt` field is a date in the format of ISO8601: `YYYY-MM-DD`. Both of these fields + [wayback machines](https://web.archive.org/) might make it easier for ppl to get to the original (untouched) image.

Due to the design of this crack, however, I wouldn't be able to show these results to the user, as this would require getting the original data from the API POST responses. This would probably be better implemented as a full-fledged browser add-on. I don't have time for that, but if anyone wants to make it, I've at least left the intel here.

POST Request example (Sent to ):
```HTTP
POST /api/search/results_page HTTP/1.1
Host: pimeyes.com
User-Agent: [REDACTED]
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://pimeyes.com/en/search/[REDACTED]
Content-Type: application/json;charset=utf-8
X-XSRF-TOKEN: [REDACTED]
Content-Length: 420
Origin: https://pimeyes.com
DNT: 1
Connection: close
Cookie: __cfduid=[REDACTED]; uploadPermissions=[REDACTED]; pimeyes_session=[REDACTED]

{"hash":"[BASE-64-PAYLOAD-HERE]","page":3,"offset":25}
```

Where `[BASE-64-PAYLOAD-HERE]` is:

```JSON
{"iv":"[UNDESIPHERABLE-REDACTED]","value":"[UNDESIPHERABLE-REDACTED-VALUE]","mac":"[UNDESIPHERABLE-REDACTED]"}
```

Where `[UNDESIPHERABLE-REDACTED-VALUE]` could be:
```BASE64
XKfPI1Qs/DUpQJj6VwpyaOpm8mSoAlEcfK7dUoe/KpUTdYO3qmReAXemkqvtvyDV/Cph3p9Wz0tIbojQJAmEQipocKVgfcYXrNFFlMg9bqAyvU2NlTl/1CijGaUh32wsbmC1HdSSYsEz4hFjC/9hcvmxn7w1DSC73/POmmZOEa4=
```

Decoding it as BASE64 only returns gibberish, so I've got no clue as to what it could be.
For now, I'll close this issue, but if you (or anybody else who reads this) wants to keep on digging, good luck! Feel free to post your progress on this issue.
